### PR TITLE
Remove example files.

### PR DESCRIPTION
**Pull request by sfayer**
These are no longer really needed as other examples are available elsewhere and we also have real agents now (for quite a while).

### CODE REVIEW

**Comment by alexanderrichards** [comment]
just quickly @sfayer do you actually want travis reporting two builds for the same thing? Do you want me to fix it such that you only have the pr one which makes most sense?

**Comment by sfayer** [comment]
Hi @alexanderrichards: Yes, please go ahead and fix this so it only does the build once...

**Comment by marianne013** [comment]
I like the example files. We should have more of those.

**Comment by sfayer** [comment]
Meh, if you want examples there are some in DIRAC itself. I'm going to merge this once we have at least one other test (so that the py.test doesn't start failing).

**Comment by alexanderrichards** [comment]
> I'm going to merge this once we have at least one other test (so that the py.test doesn't start failing).

I already have some in production, nearly ready to go.

**Comment by sfayer** [comment]
Well, perhaps we should turn off travis-ci instead considering it doesn't do anything?

**Pull request closed without merging**
