### PR TITLE
Don't delete users if a VOMS server is down

### PR DESCRIPTION
**Pull request by alexanderrichards**
This pull request should fix https://github.com/ic-hep/DIRAC/issues/51

### CODE REVIEW

**Comment by alexanderrichards** [comment]
@sfayer please review and merge

**Comment by sfayer** [comment]
Hmm, it seems https://github.com/ic-hep/GridPPDIRAC/blob/voms_server_fix/ConfigurationSystem/private/UsersAndGroupsAPI.py#L204 is still blanking the groups for servers which are down even with the patch applied...

**Comment by alexanderrichards** [comment]
thanks simon...at least they aren't getting deleted. its a step in the right direction

**Comment by alexanderrichards** [comment]
@sfayer ok round two. please review and merge.

**Pull request merged**
