### PR TITLE
Fix for missing LDAP helper functions under DIRAC v7.

### PR DESCRIPTION
**Pull request by alexanderrichards**
fix https://github.com/ic-hep/DIRAC/issues/104 (first attempt)

@sfayer this is a quick fix for the specific imports you mention. I haven't tried it on a dev box so please feel free to do so.

### CODE REVIEW

**Comment by sfayer** [comment]
I think the base class may have changed a bit:
```
Traceback (most recent call last):
  File "/opt/dirac/DIRAC/Core/Base/AgentModule.py", line 327, in am_secureCall
    result = functor(*args)
  File "/opt/dirac/GridPPDIRAC/ConfigurationSystem/Agent/AutoBdii2CSAgent.py", line 71, in execute
    if self.processSEs:
AttributeError: 'AutoBdii2CSAgent' object has no attribute 'processSEs
```

If I bypass that line, then it does appear to work.

**Comment by alexanderrichards** [comment]
> If I bypass that line, then it does appear to work.

work as in this is the only issue? I'll take a look

**Comment by alexanderrichards** [comment]
right, I've simply removed the option

**Comment by sfayer** [comment]
Thanks, looks good.

**Pull request merged**
